title : 随风的工作笔记
tagline: 记录工作中发生的点点滴滴
author :
  name : 随风
  email : eastson@outlook.com
  github : amonest
  qq : 1787585212

# 生成的HTML路径格式
permalink: /:year/:month/:day/:title

# 语法高亮显示
markdown: kramdown
highlighter: rouge


BASE_PATH: https://amonest.github.io
ASSET_PATH: false
